/**
 * Telemetry Services Index
 * 
 * This module provides a centralized export point for all telemetry-related services,
 * types, and utilities. It serves as the main entry point for the telemetry system.
 * 
 * @author Generated by GitHub Copilot
 * @version 1.0.0
 */

// Export all types
export * from './types';

// Export evaluation engine
export * from './evaluationEngine';

// Export main service
export { TelemetryService } from './telemetryService';

// Re-export commonly used functions for convenience
export { 
  evaluateTelemetryAttribute,
  evaluateMultipleAttributes,
  TelemetryEvaluationEngine
} from './evaluationEngine';

/**
 * Telemetry system version information
 */
export const TELEMETRY_VERSION = {
  major: 1,
  minor: 0,
  patch: 0,
  full: '1.0.0'
};

/**
 * Telemetry system configuration defaults
 */
export const TELEMETRY_DEFAULTS = {
  maxValuesPerAttribute: 200,
  defaultValueLimit: 50,
  batchSizeLimit: 1000,
  evaluationTimeout: 5000, // 5 seconds
  auditLogEnabled: true
};

/**
 * Telemetry system status and health checks
 */
export const TELEMETRY_STATUS = {
  HEALTHY: 'healthy',
  DEGRADED: 'degraded',
  ERROR: 'error'
} as const;

export type TelemetrySystemStatus = typeof TELEMETRY_STATUS[keyof typeof TELEMETRY_STATUS];